### PR TITLE
Floki.traverse_and_update with an accumulator

### LINKED ISSUE #246: Floki.traverse_and_update with an accumulator
## Feature goal

It would be nice if we had `Floki.traverse_and_update/3` which signature looks like:

```elixir
def traverse_and_update(html_tree, acc, fun)
```

...where `acc` is the initial value for an accumulator, and `fun` is a 2-ary function which takes a HTML node and an accumulator, and returns a 2-tuple which contains a new HTML node and a new accumulator.

With this function, we could have a functional approach to traversing and manipulating HTML trees _with a state_.

### Examples

```elixir
# Example 1: Counting the number of all HTML elements

{:ok, html_tree} =
  Floki.parse_document("""
    <h1>Hello, world!</h1>
    <p>Lorem ipsum <strong>dolor</strong> sit amet</p>
    """)
# ==> {:ok, ["..."]}

{new_tree, count} =
  Floki.traverse_and_update(html_tree, 0, fn
    elem = {name, _attr, _nodes}, acc when is_binary(name) ->
      {elem, acc + 1}

    node, acc ->
      {node, acc}
  end)
# ==> {["..."], 3}
```

```elixir
# Example 2: Assigning unique numbers to all <h2> tags
{:ok, html_tree} =
  Floki.parse_document("""
  <h1>The quick</h1>
  <h2>Brown fox</h2>
  <h3>Jumps over</h3>
  <h2>The lazy</h2>
  <h2>Dog</h2>
  """)
# ==> {:ok, [
#   {"h1", [], ["The quick"]},
#   {"h2", [], ["Brown fox"]},
#   {"h3", [], ["Jumps over"]},
#   {"h2", [], ["The lazy"]},
#   {"h2", [], ["Dog"]}]}

{new_tree, _acc} =
  Floki.traverse_and_update(html_tree, 0, fn
    {"h2", attr, nodes}, acc ->
      {{"h2", [{"data-count", to_string(acc)} | attr], nodes}, acc + 1}

    node, acc ->
      {node, acc}
  end)
# ==> {[
#   {"h1", [], ["The quick"]},
#   {"h2", [{"data-count", "0"}], ["Brown fox"]},
#   {"h3", [], ["Jumps over"]},
#   {"h2", [{"data-count", "1"}], ["The lazy"]},
#   {"h2", [{"data-count", "2"}], ["Dog"]}], 3}
```

I would like to submit a pull request if you think this feature is good for this project.

### PR DESCRIPTION
**Pull request by Dalgona**
Closes #246.

This pull request will add the `Floki.traverse_and_update/3` function, which is described in the above issue.

Aside from that:

- In 48799f9b2851a0fc91a6bc5172a1343a806d341a, I tried to reorganize existing function clauses in `Floki.Traversal` to make the code look more concise.
- And in 1ef0529f94adda7218fbe425d769c185f8c6a650, I tried modifying the existing function documentation of `Floki.traverse_and_update/2` to make it look nicer in ExDoc documentation.

Please let me know if there is anything I have missed. :smile:

### CODE REVIEW

**Comment by philss** [comment]
@Dalgona Thank you! It looks great! :purple_heart: 

I'm going to squash the commits and condensate in one commit, OK? I think these changes can look more atomic if we squash.

**Comment by Dalgona** [comment]
That sounds great! Please go ahead. 🚀

**Comment by philss** [comment]
@Dalgona I did manually and the result is this commit: https://github.com/philss/floki/commit/4f4517404bda72e5fc43e71a4df20364f8c79911 
I already merged with master, so I'm closing this.

Once again, thank you!

**Comment by philss** [comment]
And I forgot to mention that I added type specs.

**Comment by Dalgona** [comment]
@philss Good! And thank you for adding type specs! 🥰 But I see something that we can improve:

https://github.com/philss/floki/blob/4f4517404bda72e5fc43e71a4df20364f8c79911/lib/floki.ex#L386...L391

First, we should say that this function should return values with `{html_tree(), traverse_acc()}` type, not `html_tree()`.

Also, we don't need `traverse_acc()` as a separate type; we can refactor the spec using a guard. So the final type spec I suggest for `traverse_and_update/3` looks like:

```elixir
@spec traverse_and_update(
        html_tree(),
        traverse_acc(),
        (html_tag(), traverse_acc() -> {html_tag() | nil, traverse_acc()})
      ) :: {html_tree(), traverse_acc()} when traverse_acc: any()
```

Thank you for merging this pull request, and I hope we could fix this in another commit. 😁

**Comment by Dalgona** [comment]
well, it seems that no one's gonna be notified for coments on closed prs. /shrug

**Comment by philss** [comment]
@Dalgona OMG, sorry for not answering it 😞 

The first thing was fixed by https://github.com/philss/floki/commit/d07358cee67a70f2973b6d9997dbf11067b3d602. 

I didn't know about the "when" of `@spec`. Do you mind to open a PR with that change? Thank you!

**Pull request closed without merging**
