### PR TITLE
Allow root nodes to be selected using pseudo-classes

### LINKED ISSUE #385: Pseudo selectors do not find top-level elements
## Description

The pseudo selector queries appear to ignore top-level elements.

## To Reproduce

- Using Floki v0.32.0
- Using Elixir v1.12.3
- Using Erlang OTP v23
- With this code:

```elixir
iex> tree = Floki.parse_fragment!("<p>A</p>")
[{"p", [], ["A"]}, {"p", [], ["B"]}]

iex> Floki.find(tree, "p:nth-child(1)")
[]

iex> Floki.find(tree, "p:nth-of-type(1)")
[]

iex> Floki.find(tree, "p:first-child")
[]
```

## Expected behavior

I find this behavior to be inconsistent with other methods of querying. For example:

```elixir
iex> tree = Floki.parse_fragment!("<p id=\"a\">A</p>")
[{"p", [{"id", "a"}], ["A"]}]

iex> Floki.find(tree, "p")
[{"p", [], ["A"]}, {"p", [], ["B"]}]

iex> Floki.find(tree, "p#a")
[{"p", [{"id", "a"}], ["A"]}]
```

Also, consider that in a browser, all of the following examples will return the root HTML node:

```javascript
document.querySelector("html");
document.querySelector("html:nth-child(1)");
document.querySelector("html:nth-of-type(1)");
document.querySelector("html:first-child");
```

### PR DESCRIPTION
**Pull request by rzane**
Fixes #385

### CODE REVIEW

**Comment by philss** [comment]
@rzane thank you for this PR (and for open the issue) :purple_heart: 

I think the failures is due the fact that `html5ever` implementation does not support `parse_fragment` yet.
I would suggest to use the tag `:except_parser` to skip the tests for that one.

```elixir
# There is an alias in the file, so you can just call `Html5ever`
@tag except_parser: Html5ever
test "your test"
```

**Comment by rzane** [comment]
Okay, I'll fix that in the bit. I hope you don't mind me taking a crack at a bit of a refactor. Happy to revert!

**Comment by philss** [comment]
>  I hope you don't mind me taking a crack at a bit of a refactor. Happy to revert!

No problem! But if starts to get too big I will suggest to open another PR :)

**Comment by rzane** [comment]
No, that's as far as I'm taking it. I was just trying to remove some of the duplication that I introduced.

**Comment by rzane** [comment]
This should be ready now. Not sure why, but the CI workflow only ran for the initial PR creation.

**Comment by philss** [comment]
@rzane it's because I need to run manually for PRs of contributors.

**Comment by philss** [comment]
@rzane awesome! Thank you!

**Pull request merged**
