### PR TITLE
first attempt at transform function

### PR DESCRIPTION
**Pull request by bobjflong**
fixes https://github.com/philss/floki/issues/65

Just uses Elixir's pattern matching on the html tree structure. This is how I'd implement the function outside of the library. Maybe there's a more efficient way using Floki's selector engine?

### CODE REVIEW

**Comment by rstacruz** [comment]
Aw yiss, this is very useful.

**Comment by rstacruz** [comment]
I'd also love a way to pass a selector to the transformation, just like `Floki.find`:

```ex
Floki.transform(html, "a[href^=\"http\"]", &add_class/1)

def add_class({tag, attrs, children}) do
  {tag, [class: "external"] ++ attrs, children}
end
```

**Comment by philss** [comment]
@bobjflong Thank you for the PR! And sorry for the delay!

I'm gonna merge this, and try to improve a little bit.

The ideal solution is to make it work by updating the HTML tree. Not sure if it's possible in the current code.

**Comment by philss** [comment]
@rstacruz Cool! This is the ideal API.

But I'm not sure if it's clear that we are transforming the HTML tree or only the results of selector.

```html
<html>
  <body>
    <h1>Example</h1>
    <ul>
      <li><a href="http://external.com">Link to external</a></li>
      <li><a href="/home">Link to home</a></li>
    </ul>
  </body>
</html>
```

The Elixir code:

```elixir
Floki.transform(html, "a[href^=\"http\"]", &add_class/1)

def add_class({tag, attrs, children}) do
  {tag, [class: "external"] ++ attrs, children}
end
```

1. Update the tree will return:

```elixir
{"html", [],
 [{"body", [],
   [{"h1", [], ["Example"]},
    {"ul", [],
     [{"li", [],
       [{"a", [{:class, "external"}, {"href", "http://external.com"}], ["Link to external"]}]},
      {"li", [], [{"a", [{"href", "/home"}], ["Link to home"]}]}]}]}]}
```

2. Update and return only results:

```elixir
[{"a", [{:class, "external"}, {"href", "http://external.com"}], ["Link to external"]}]
```

In my opinion, the user is expecting the first option. What do you think?

**Comment by philss** [comment]
@bobjflong This is released in version [v0.11.0](https://hex.pm/packages/floki/0.11.0). Thanks again!

PS: I'm working in a version to receive the selector update and the tree, as we talked here. I hope to finish this soon. I will let you know. cc @rstacruz

**Pull request merged**
