### PR TITLE
Fix issue when finding fails if html begins with xml tag

### PR DESCRIPTION
**Pull request by sergey-kintsel**

### CODE REVIEW

**Comment by philss** [comment]
Hi @sergey-kintsel, thank you for this PR.

I'm not sure if this is the same issue that was fixed by #111 . Can you check, please?
Also, if this issue is different, please update your branch with master.

**Comment by sergey-kintsel** [comment]
Hi @philss! I rebased on master, commented my crutch-line in `selector.ex` and my spec failed. So, I assume that this is needed :-)

**Comment by philss** [comment]
@sergey-kintsel OK, thank you! 😃

**Comment by philss** [comment]
I forgot to mention that this fix was released in version 0.17.1.

**Pull request merged**
