### PR TITLE
Fix typespec for filter_out

### PR DESCRIPTION
**Pull request by myfreeweb**
ElixirLS was complaining about `Floki.filter_out(_, :comment)`

### CODE REVIEW

**Comment by ckruse** [comment]
Ha. Noticed this, too.

**Comment by philss** [comment]
Nice catch, @myfreeweb!
Can you run the formatter on those files and amend the commit, please?

**Comment by myfreeweb** [comment]
done

**Comment by philss** [comment]
@myfreeweb thank you!

**Pull request merged**
